from enum import Enum


class MeasureDispersionType(str, Enum):
    CONFIDENCE_80 = "CONFIDENCE_80"
    CONFIDENCE_90 = "CONFIDENCE_90"
    CONFIDENCE_95 = "CONFIDENCE_95"
    CONFIDENCE_975 = "CONFIDENCE_975"
    CONFIDENCE_99 = "CONFIDENCE_99"
    CONFIDENCE_OTHER = "CONFIDENCE_OTHER"
    FULL_RANGE = "FULL_RANGE"
    GEOMETRIC_COEFFICIENT = "GEOMETRIC_COEFFICIENT"
    INTER_QUARTILE_RANGE = "INTER_QUARTILE_RANGE"
    NA = "NA"
    STANDARD_DEVIATION = "STANDARD_DEVIATION"
    STANDARD_ERROR = "STANDARD_ERROR"

    def __str__(self) -> str:
        return str(self.value)
