from enum import Enum


class NonInferiorityType(str, Enum):
    EQUIVALENCE = "EQUIVALENCE"
    NON_INFERIORITY = "NON_INFERIORITY"
    NON_INFERIORITY_OR_EQUIVALENCE = "NON_INFERIORITY_OR_EQUIVALENCE"
    NON_INFERIORITY_OR_EQUIVALENCE_LEGACY = "NON_INFERIORITY_OR_EQUIVALENCE_LEGACY"
    OTHER = "OTHER"
    SUPERIORITY = "SUPERIORITY"
    SUPERIORITY_OR_OTHER = "SUPERIORITY_OR_OTHER"
    SUPERIORITY_OR_OTHER_LEGACY = "SUPERIORITY_OR_OTHER_LEGACY"

    def __str__(self) -> str:
        return str(self.value)
