from enum import Enum


class Status(str, Enum):
    ACTIVE_NOT_RECRUITING = "ACTIVE_NOT_RECRUITING"
    APPROVED_FOR_MARKETING = "APPROVED_FOR_MARKETING"
    AVAILABLE = "AVAILABLE"
    COMPLETED = "COMPLETED"
    ENROLLING_BY_INVITATION = "ENROLLING_BY_INVITATION"
    NOT_YET_RECRUITING = "NOT_YET_RECRUITING"
    NO_LONGER_AVAILABLE = "NO_LONGER_AVAILABLE"
    RECRUITING = "RECRUITING"
    SUSPENDED = "SUSPENDED"
    TEMPORARILY_NOT_AVAILABLE = "TEMPORARILY_NOT_AVAILABLE"
    TERMINATED = "TERMINATED"
    UNKNOWN = "UNKNOWN"
    WITHDRAWN = "WITHDRAWN"
    WITHHELD = "WITHHELD"

    def __str__(self) -> str:
        return str(self.value)
